### PR TITLE
Add support for variable expansion

### PR DESCRIPTION
**Pull request by eddsteel**
I wanted to be able to use ${USER} in an env value, so that each
member of a team would have a distinct value for that variable without
modifying `.env`.

This will allow for expansion of variables in env values, taking from
the system environment or other values in the env file (it works once
the env file is parsed).

You can use nesting and chains of references, up to 3 deep (the tests
should clarify). Using 3 was arbitrary but I doubt anyone needs more.

Unfortunately I couldn't think of a way of reliably testing the plugin
with system environment variables that would work for both travis and
local dev, but I've tested it manually.

### CODE REVIEW

**Comment by eddsteel** [comment]
I think the codacy check is a false positive; there are two `+`s but they're either side of a disjunction (`|`).

**Comment by mefellows** [comment]
Thanks @eddsteel, this sounds great. I'll aim to look at this during the week!

**Comment by eddsteel** [comment]
I guess I shouldn't have modified the README when it's not yet released... 😅 Is a new release on the cards?

**Comment by eddsteel** [comment]
Never mind, I hadn't realised the project auto publishes each merge to master. Nice!

**Comment by mefellows** [comment]
Great, 'coz I was about to freak out that a bunch of changes are probably not there! 👍

**Pull request merged**
